### ISSUE TITLE
Game doesn't fail when you hit the wall

### ISSUE THREAD

**Issue by karlmikko** [Slowyn/js-snake#1]

**Comment by Slowyn** [comment]
Yeah, I was thinking about this part of game while designing and decided to take as an etalon Nokia 3310 Snake in which there were not walls. But setting a wall as a rule would make game a bit harder and also a bit easier in implementation. I think it would fit good with Reverse time feature. So yeah, it does make sense.

**Comment by karlmikko** [comment]
Maybe it could just be an option - for different rules. I forgot the 3310 did wrap around
